led_matrix_compositor:
  ros__parameters:
    # Топик для отправки данных в драйвер
    output_topic: led_matrix/data
    
    # Топик для приема изображений для логических групп
    input_topic: panel_image